---
title: "Rmarkdown continued"
author: "Mike Smith"
date: "`r Sys.Date()`"
output: 
    html_document: 
        df_print: paged
editor_options: 
  chunk_output_type: console
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  echo=TRUE,
  warning=FALSE,
  error=TRUE,# keep running even if error encountered
  message=FALSE)
```

```{r, load-libraries}
library(dplyr)
library(ggplot2)
```

Here we check if we've already downloaded the data.  If we have, read it, otherwise download and save a copy for next time.

```{r import-data, eval = TRUE, echo = FALSE}
rdsPath <- "gapminder-FiveYearData.rds"
if(!file.exists(rdsPath)){
  gappy <- read.table('http://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv',
                      header=TRUE, sep=',',strip.white = T)
  saveRDS(gappy,file = rdsPath)
}else{
  gappy <- readRDS(file = rdsPath)
}
```

Here we select only the countries that start with 'A' and plot the life expentency against time for each one.

```{r print-gappy, eval = TRUE}
gappy %>%
  filter(stringr::str_starts(country, "A")) %>%
  ggplot(aes(x = year, y = lifeExp)) +
  geom_point() +
  facet_wrap(facets = "country")
```
