---
title: "Rmarkdown continued"
author: "Mike Smith"
date: "`r Sys.Date()`"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
## This sets default values for chunk options
knitr::opts_chunk$set(
  echo=TRUE,
  warning=FALSE,
  error=TRUE,# keep running even if error encountered
  message=FALSE)
```

Here we check if we've already downloaded the data.  If we have, read it, otherwise download and save a copy for next time.

```{r import-data, eval = TRUE, echo = FALSE}
rdsPath <- "gapminder-FiveYearData.rds"
if(!file.exists(rdsPath)){
  gappy <- read.table('http://raw.githubusercontent.com/resbaz/r-novice-gapminder-files/master/data/gapminder-FiveYearData.csv',
                      header=TRUE, sep=',',strip.white = T)
  saveRDS(gappy,file = rdsPath)
}else{
  gappy <- readRDS(file = rdsPath)
}
```

We can print the contents of a data frame, but it looks pretty ugly.  There are ways to make this nicer e.g.
  
- df_print: paged
- knitr::kable (digits, align, caption)
- DT::datatable

```{r print-gappy, eval = TRUE}
gappy[1:20,]
```

